Repository Cortuzz/WeebAlgorithms, pull requests merged in 2022-03, with the labels that each got.

#8 Realized path finder with step-by-step visualizing
  src/css/nav.css
  src/css/path_finder.css
  src/js/main.js
  src/js/path_finder/finder.js
  src/js/path_finder/handler.js
  src/templates/path_finder.html
Labels: enhancement

#13 Dimensions view, fixes
  src/js/path_finder/handler.js
  src/templates/path_finder.html
Labels: bug, enhancement

#14 Field randomizer, Speed control
  src/css/path_finder.css
  src/js/path_finder/finder.js
  src/js/path_finder/handler.js
  src/templates/path_finder.html
Labels: enhancement

#19 Useful functions
  src/js/main.js
Labels: enhancement

#20 Ants basic
  index.html
  src/css/ants_basic.css
  src/css/checkbox.css
  src/css/path_finder.css
  src/js/ants_basic/ants.js
  src/js/ants_basic/handler.js
  src/js/ants_basic/params.js
  src/templates/ants_basic.html
  src/templates/clustering.html
  src/templates/genetic.html
  src/templates/neural_network.html
  src/templates/path_finder.html
Labels: enhancement

#23 fixed #22
  src/js/path_finder/handler.js
Labels: bug

#24 Clustering bruh
  src/css/clustering.css
  src/js/clustering/clustering.js
  src/js/clustering/handler.js
  src/js/main.js
  src/templates/clustering.html
  src/templates/path_finder.html
Labels: enhancement

#25 enhancement some features
  index.html
  src/css/animation.css
  src/css/clustering.css
  src/css/nav.css
  src/img/background.jpg
  src/img/flying.png
  src/img/jibr.jpg
  src/js/clustering/clustering.js
  src/templates/ants_basic.html
  src/templates/clustering.html
  src/templates/genetic.html
  src/templates/neural_network.html
  src/templates/path_finder.html
Labels: enhancement

#26 Changed http to https
  src/templates/clustering.html
  src/templates/path_finder.html
Labels: bug

#27 Buttons & Sliders
  src/css/button.css
  src/css/nav.css
  src/js/ants_basic/ants.js
  src/js/ants_basic/handler.js
  src/templates/ants_basic.html
Labels: enhancement

#31 Path finder fix
  src/css/nav.css
  src/css/path_finder.css
  src/js/path_finder/handler.js
Labels: bug, enhancement

#33 Hot fix
  src/css/clustering.css
  src/js/clustering/clustering.js
  src/js/clustering/handler.js
  src/templates/clustering.html
Labels: bug

#34 Hot fix
  src/js/clustering/clustering.js
Labels: bug
